#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=UpdateEnvironmentWithPip
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=slurm_output_update_environment_with_pip_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Activate your environment
source activate universal_encoder_env
# srun python -m pip install <package_name>
